title: Sujay Bagi # your name (or website title) here
logo: "/images/sujay.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Materials Scientist and Research Assistant
  <br><br>
  MIT
  <br><br>
  <a href="https://www.linkedin.com/in/sujay-bagi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
