title: Sujay Bagi # your name (or website title) here
logo: "/images/sujay.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Materials Scientist and Research Assistant (TATA Fellow)
  <br><br>
  MIT (Massachusetts Institute of Technology)
  <br><br>
  <a href="https://www.linkedin.com/in/sujay-bagi/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="pdf/sample_presentation.pdf/">View My Resume</a>
  <br><br>
  <a href="https://scholar.google.com/citations?user=ap8CUAcAAAAJ&hl=en&oi=ao">View My Google Scholar</a> 
  <br><br>
  <a href="https://www.romangroup.mit.edu/">View My Research Lab</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
