title: Sujay Bagi # your name (or website title) here
logo: "/images/Sujay1a.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <a href="https://www.linkedin.com/in/sujay-bagi/">View My LinkedIn Profile</a> <br>
  <a href="https://www.dropbox.com/s/ct8ue4f12to81nd/Sujay%20Bagi-Resume%20-%20MIT.pdf?dl=0">View My Resume</a> <br>
  <a href="https://scholar.google.com/citations?user=ap8CUAcAAAAJ&hl=en&oi=ao">View My Google Scholar</a> <br>
  <a href="https://www.romangroup.mit.edu/">View My Research Lab</a>
  <br>
  I'm a PhD candidate at MIT working for Prof Yuriy Roman. My background at the intersection of mechanical engineering, materials science, & chemical engineering positions me to understand and efficiently tackle real-world challenges. 
  <<br>
  I'm interested in areas related to renewable energy technologies, materials synthesis, crystallization science, techno-economic modelling, energy storage, carbon capture, sustainable water supply, automotive emissions, fuels, and policy.
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
